# Change these first
owner: Nookturnal # Your GitHub organization or username, where this repository lives
repo: nookturnal-upptime # The name of this repository

sites:
  - name: Nookturnal Lab
    url: https://www.nookturnal.com/
  - name: StaffConnect Solutions
    url: https://www.staffconnect.ph/
  - name: Zugbu Aesthetic
    url: https://www.zugbuaesthetic.com/
  - name: Taskforge Global
    url: https://www.taskforgeglobal.com/
  - name: KAYA Music Studio
    url: https://www.kayamusicstudio.com/
  - name: Property Portal
    url: https://www.propertyportal.ph/
  - name: Topnotch Real Estate Review Center
    url: https://www.topnotchreviewcenter.com/

status-website:
  cname: status.nookturnal.com
  favicon: https://cloud-1de12d.b-cdn.net/media/original/31d188d960df32513b2beb3c6c707491.png
  name: Nookturnal Lab
  logoUrl: https://cloud-1de12d.b-cdn.net/media/original/31d188d960df32513b2beb3c6c707491.png
  introTitle: "This page displays the uptime status of our projects."
  introMessage: —————————
  navbar:
    - title: Home
      href: https://www.nookturnal.com/
    - title: Status
      href: /
  metaTags:
    - name: "robots"
      content: "noindex"


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
